### ISSUE TITLE
Featured topics overflow into sidebar on small screens

### ISSUE THREAD

**Issue by frjo** [ResetNetwork/recoding-tech#104]
![Skärmavbild 2022-03-21 kl  15 10 17](https://user-images.githubusercontent.com/191392/159307148-7c418897-86f3-4233-891a-56e09a04c9ff.png)
![Skärmavbild 2022-03-21 kl  15 10 40](https://user-images.githubusercontent.com/191392/159307159-220d34ac-ce31-45e3-99fe-cac56d8e761f.png)

**Comment by harumhelmy** [comment]
thanks for catching @frjo! Pushed a fix to the test site: https://test.recoding.tech/
