### ISSUE TITLE
add table of contents to article pages 

### ISSUE THREAD

**Issue by katiewilson21** [ResetNetwork/recoding-tech#109]
see design here: https://www.figma.com/file/L9szOsvQdhyumMOGEz4VnI/?node-id=0%3A1 "Updated article" frame 

Generate links in a numbered list from H1 headings only.

**Comment by harumhelmy** [comment]
This should be trivial but has potential to be non-trivial! I'll have a better ETA next week, but aiming to be done with this by next Friday.

**Comment by harumhelmy** [comment]
@katiewilson21 The ToC is up on the test site -- it's not clickable yet, making the hash links work is proving to be tricky because of how we set up the backend. No ETA on that yet, sorry

**Comment by harumhelmy** [comment]
Yayyy the hash links now work!
