### ISSUE TITLE
Site not updating 

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#113]
@jheretic @rudietuesdays @harumhelmy the site does not seem to be updating this morning. I've posted a new article and made it the featured article on the homepage in the CMS, but nothing has changed. It's been a half hour since I made the changes/additions in the CMS. I've cleared my cookies/caches multiple times, but nothing. This is holding up putting out the monthly newsletter. 

This is the article that should be featured: https://recoding.tech/article/how-russias-invasion-of-ukraine-changes-the-conversation-about-governing-big-tech/. Also, I've add topic tags to it as well that aren't showing up either.

**Comment by gt150** [comment]
@harumhelmy Thanks. I wonder if what might be the problem is me using the related topics. I forgot that we changed how the articles showed up on the topic pages to be manually added to each page rather than automatically by related topics. I wonder if I removed the related topics, if that would fix the problem.

**Comment by harumhelmy** [comment]
Ah, interesting! I think it might be related to that, because I think it is with something with how Stackbit interacts with some of the Sanity datasets -- it creates file sizes that are just too big, making the build fail. It's a problem for which I have a partial fix, but just had been testing it locally. Going to test it on production now and keep you posted @gt150. Don't remove the related topics just yet (though it's fine if you already have by the time you read this!)

**Comment by gt150** [comment]
@harumhelmy do you have an eta on the fix? As I noted above, this issue is holding up putting out the monthly newsletter. I'm not trying to unneccesarily rush you, but I just need to know if you think it can be fixed today, or if I need to push the release to tomorrow.

**Comment by yaelrst** [comment]
Just checked in with @harumhelmy and they are getting close to a fix. Time estimate within the hour

**Comment by jheretic** [comment]
@gt150 Deploying a probable fix now, hopefully will have an update within a few minutes.

**Comment by harumhelmy** [comment]
Hey @gt150 @yaelrst! I'm really sorry but the fix is still not working -- we're trying out a couple more ideas now and will keep working on this, but really not sure if it'll be fixed today.

**Comment by gt150** [comment]
@harumhelmy I understand. Is it possible to just remove the topic tags on the article. Would that get us unstuck for now, and give you Josh time to figure out the longer term fix.

**Comment by harumhelmy** [comment]
Oh yeah we can try that, @gt150! I'll go into Sanity and remove those and see if that changes anything, I'll keep track of what they are so we can add them back later

**Comment by gt150** [comment]
@harumhelmy seems like this is not going to be a quick fix. Can we just delete the article or revert the site to before I did whatever I did to cause the problem?

**Comment by gt150** [comment]
@harumhelmy nm. It's working now!!!

**Comment by jheretic** [comment]
Hey @gt150 we just finished reworking the build process to exclude the cache file that was making the build too large to deploy, and we believe it is working correctly and deployed now. Sorry for the delay.

**Comment by jheretic** [comment]
As a side note with these build changes even more of the site is statically generated and optimized ahead of time, so it may be faster than before. Going to go ahead and close this out.
