### ISSUE TITLE
standardize article cards 

### ISSUE THREAD

**Issue by katiewilson21** [ResetNetwork/recoding-tech#115]
Overline text (ie "commentary") = Lexend Semibold 14pt, all caps 
Title text = Lexend Semibold, 24pt, Title case 
Author = Lexend Medium, 12pt, all caps
Date = Libre Baskerville Italic, 12 pt, Title Case
increase spacing a touch between author and date lines

like this:
<img width="988" alt="image" src="https://user-images.githubusercontent.com/84089903/165977627-388aeb87-0f02-490f-a92c-9f367fb06d5d.png">

(currently, inconsistent: 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/84089903/165977323-9e4d3ac4-f7aa-4fa1-a8f7-ec0f8e8d7edd.png">
vs 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/84089903/165977373-0529f259-efc8-4797-a90d-078b26278baa.png">
)

**Comment by harumhelmy** [comment]
I pushed some updates to the test site with these changes @katiewilson21! I don't think I got the author style correct yet, will push that up next

**Comment by katiewilson21** [comment]
great!
