### ISSUE TITLE
Text styling updates 

### ISSUE THREAD

**Issue by katiewilson21** [ResetNetwork/recoding-tech#118]
@harumhelmy as we discussed, can we try these sizes: 

**FANCY / ARTICLE BOX:**
title: Lexend Semibold, 20pt. Title case. 
author: Lexend medium, 10pt. all caps.
date: Libre Baskerville regular italic, 10pt, title case. 

**MAIN COLUMN (LEFT)** 
Headings (ie “Featured topics”): Lexend  bold, 16pt, all caps 
Subheadings (ie “new issues, policies..”) = Libre baskerville regular italics, 14pt 

**RIGHT COLUMN:** 
Headings (ie “latest headlines and highlights”) = Lexend  bold, 12pt, all caps 
View all links = Lexend  bold, 12pt, all caps (red) 

**Keep citations/headlines and highlights entries the same**

**Newsletter sign up text:** change to 12pt

**Policy tracker:** 
Decrease title card text by 2px, keep everything else the same.

**Comment by harumhelmy** [comment]
Hi hi @katiewilson21! Most of these updates are up on the test site! A couple questions: 

- Can you confirm whether the article boxes on the homepage should have the "Commentary" or "Commentary and Analysis" supertitle thing?
-  Decided to use ellipses to truncate the titles of policy actions in the homepage tracker table. What do you think?
