### ISSUE TITLE
Adjust article card alignment on issues/policy pages 

### ISSUE THREAD

**Issue by katiewilson21** [ResetNetwork/recoding-tech#119]
align the title text with the rest of the right column

like this: 
<img width="396" alt="image" src="https://user-images.githubusercontent.com/84089903/169615052-9a1ad704-efd7-458e-b0ce-62269f89b4f7.png">

currently: 

<img width="489" alt="image" src="https://user-images.githubusercontent.com/84089903/169615128-605c3673-d9ee-41a7-81ad-769fc054da66.png">

**Comment by harumhelmy** [comment]
Going to be working on these next -- aiming to get them done by the end of the week!

**Comment by harumhelmy** [comment]
Up on the test site!

**Comment by katiewilson21** [comment]
looks great! @harumhelmy
