### ISSUE TITLE
Policy tracker item not updating 

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#123]
Made changes to this in the CMS yesterday, but it's not updating on the site.
https://recoding.tech/tracker/digital-services-act/

**Comment by jheretic** [comment]
Hi @gt150,

We can see that the build is failing, we're looking into it and should have an update for you tomorrow.

**Comment by harumhelmy** [comment]
Hey folks! We're still working on this issue, just fyi -- we'll have a more thorough update tomorrow.

**Comment by danblah** [comment]
Is this related to there now being nothing there (or in the citations)?

**Comment by gt150** [comment]
the issue was fixed.
