### ISSUE TITLE
On homepage, the green/gray wave thing behind the banner text is barely visible, make it a shade or two darker

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#13]

**Comment by rudietuesdays** [comment]
@katiewilson21 can you suggest a hex or RGBA code to use? Thanks!

**Comment by katiewilson21** [comment]
Try #DFE7E6

**Comment by katiewilson21** [comment]
Try #DFE7E6

**Comment by harumhelmy** [comment]
This is with #DFE7E6, what do we think?

![Screen Shot 2021-12-29 at 12 18 03](https://user-images.githubusercontent.com/13320420/147687493-37020ab9-8115-4277-924f-a09c63fdfdfc.png)

**Comment by danblah** [comment]
that def stands out more. im good to go with whatever @katiewilson21 says!

**Comment by katiewilson21** [comment]
sorry, didn't respond -- yes, looks good!! @harumhelmy

**Comment by rudietuesdays** [comment]
Ok to close @katiewilson21 @danblah ?
