### ISSUE TITLE
In studio, make layout for issues a required field

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#24]

**Comment by harumhelmy** [comment]
I'm actually not sure what this is referring to. @rudietuesdays do you know off the top of your head? if not I'll flag @danblah

**Comment by rudietuesdays** [comment]
Hmmm I assume it's on the Topics content type, the field "Type of topic"? But yeah @danblah plz verify

**Comment by harumhelmy** [comment]
Ah yes that's already required: 
<img width="748" alt="Screen Shot 2021-11-18 at 17 02 02" src="https://user-images.githubusercontent.com/13320420/142503965-d114ff91-d3b5-49f3-bd57-8b1ef0f4ddf2.png">

**Comment by rudietuesdays** [comment]
Oh great! @danblah good to close out this issue?

**Comment by danblah** [comment]
yes, all good, closing
