### ISSUE TITLE
Investigate citations build error

### ISSUE THREAD

**Issue by rudietuesdays** [ResetNetwork/recoding-tech#29]
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @next/swc-darwin-arm64@12.0.2: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  arm64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-11-15T1***_06_20_145Z-debug.log
Error: Process completed with exit code 1.

**Comment by danblah** [comment]
Could I get an eta on this and thanks for posting here!

**Comment by jheretic** [comment]
This was just an error due to a build artifact that got committed erroneously. It didn't cause any data issues, and is now fixed.
