### ISSUE TITLE
Within a Policy Action (FTC vs. Facebook, Inc.) is assigned a Related Topic (ie Facebook), should the Related Topic's page auto update to show the Policy Action or should it be a manual process?

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#39]
See https://recoding-tech-2d607.sanity.studio/desk/policy_action;caa1b89e-3640-4829-944d-89f87ce9b498
See https://recoding-tech-v2.netlify.app/company/facebook and https://recoding-tech-2d607.sanity.studio/desk/topic;facebook1
See

**Comment by gt150** [comment]
when I add a new policy action that i've tagged for Facebook for example, it should show up automatically on the Facebook page and similarly on any other pages I've tagged as related topics.

**Comment by danblah** [comment]
Thank you! Closing this as answered!
