### ISSUE TITLE
Quick start guides aren't showing up on the homepage

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#41]
See https://recoding-tech-2d607.sanity.studio/desk/guide that should be showing up on https://recoding-tech-v2.netlify.app/ at the bottom right?

**Comment by danblah** [comment]
Deadline?

**Comment by harumhelmy** [comment]
@danblah Just opened a PR, pending a review from @jheretic (they'll likely get to it tomorrow!)

**Comment by danblah** [comment]
See them!
