### ISSUE TITLE
Need Policy Actions created that are associated to Antitrust 

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#42]
Need these to review the page against the designs for testing

**Comment by gt150** [comment]
They're already seven policy actions associated with antitrust in the cms. They are tagged for antitrust under related topics. They are not showing up on the antitrust page.

**Comment by danblah** [comment]
Am i looking at the right thing here: https://recoding-tech-2d607.sanity.studio/desk/topic;antitrust

Don't see any "Related law and government tracker actions" associated there. 

I think this might be related to #19

**Comment by danblah** [comment]
Just manually added the Policy Actions that were tagged as antitrust to that antitrust page. Closing this as good/done for me, thank!
