### ISSUE TITLE
Citation lists on the website (aka Latest Headlines & Highlights) are not listing as expected

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#44]
On homepage
* This should show the 6 most recently published (by zotero date field) citations

On Search
* This should be in the order of recently published (by zotero date field)

On Topic pages (aka Issues, Policies, Country, and Company)
* This show the most recent 3 in the order of recently published ( by zotero date field) 
* The view all should go to the search page pre-filtered for that topic

**Comment by danblah** [comment]
Deadline?

**Comment by harumhelmy** [comment]
I have a partial fix for this -- aiming for Tuesday (trying to underpromise and overdeliver!)

**Comment by danblah** [comment]
@jheretic @harumhelmy im still not seeing any "Latest headlines & Highlights" on any topic pages (aka Issues, Policies, Country, and Company) as is in the wireframes.

bump bump bump!

**Comment by danblah** [comment]
@harumhelmy this a dupe of #23? if so can we close this one?

**Comment by rudietuesdays** [comment]
@danblah Yes I believe this is a dupe of #23 which is now fixed, so I'm all for closing this one

**Comment by rudietuesdays** [comment]
Closing as a dupe of #23 -- feel free to reopen if needed!
