### ISSUE TITLE
Clicking a policy action link (in antitrust) creates a application error: something clientside and breaks everything

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#45]
https://recoding-tech-v2.netlify.app/tracker/[object%20Object] Also has this super weird link

https://recoding-tech-v2.netlify.app/issue/monopolization also creates this error

**Comment by danblah** [comment]
Still happening. Can we get a deadline on resolving this?

**Comment by harumhelmy** [comment]
Ready for testing! @danblah

**Comment by gt150** [comment]
https://recoding-tech-v2.netlify.app/issue/monopolization Now works along with other issue and policy pages.  https://recoding-tech-v2.netlify.app/tracker Still problems with law & regulation tracker. Every link is broken and lists https://recoding-tech-v2.netlify.app/[object%20Object].

**Comment by harumhelmy** [comment]
Oh thanks for catching that! Will update with a fix in a minute @gt150

**Comment by harumhelmy** [comment]
This is ready for another look @gt150!

**Comment by gt150** [comment]
@harumhelmy links for policy actions look fixed!

**Comment by danblah** [comment]
Resloved!
