### ISSUE TITLE
Spell check changes are undone when publishing content

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#52]
When using the spell check functionality in the CMS, the text reverts back to the original misspelled word when the user hits publish button.

**Comment by harumhelmy** [comment]
Hey @gt150 -- this spellcheck feature is built-in from Sanity, so the quickest thing we can do is turn it off. Debugging that is probably beyond our scope/would take too long. How does that sound?

**Comment by gt150** [comment]
@harumhelmy nm, then. Leave the spellcheck on.
