### ISSUE TITLE
Further reading is not showing up on law and regulation items

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#55]
For example, a further reading item was added in the CMS for https://recoding-tech-v2.netlify.app/tracker/safe-tech-act, but it's not showing up on the devsite.

**Comment by harumhelmy** [comment]
Update: this issue in itself has a fix now, but there's just a couple of styling issues with that column that @rudietuesdays is helping me out with!

**Comment by harumhelmy** [comment]
Fixed!

**Comment by danblah** [comment]
WHOOP!
