### ISSUE TITLE
[mobile] can we hide the menu with a hamburger icon so that the content is easier to see?

### ISSUE THREAD

**Issue by katiewilson21** [ResetNetwork/recoding-tech#60]
note: will offer a design to make the menu less awkward in mobile next week

**Comment by rudietuesdays** [comment]
Waiting on design, thank you!

**Comment by katiewilson21** [comment]
![image](https://user-images.githubusercontent.com/84089903/150382315-835e4825-d5fe-4e56-a04d-479f17459fd0.png)


tried to make it lightweight -- lmk how that looks

**Comment by rudietuesdays** [comment]
Looks great! I'll implement, thanks.

**Comment by rudietuesdays** [comment]
Mobile menu added! Let me know what you think.

**Comment by katiewilson21** [comment]
looks amazing, thanks!

**Comment by danblah** [comment]
Lovely
