### ISSUE TITLE
duplicates showing up in citation feed

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#62]
<img width="1218" alt="Screen Shot 2022-01-10 at 10 36 44 AM" src="https://user-images.githubusercontent.com/9727494/148794403-0c7d4f3f-ea08-4b60-88e8-02fc4e2303c3.png">
<img width="480" alt="Screen Shot 2022-01-10 at 10 36 29 AM" src="https://user-images.githubusercontent.com/9727494/148794414-e7e5198e-786b-4d8b-aecc-5f7c261fecd8.png">

**Comment by gt150** [comment]
The second items is the only citation that should be showing up. There is no duplicate in the CMS so I'm not sure how this got created, maybe a caching issue?

**Comment by danblah** [comment]
I'm still seeing this

**Comment by rudietuesdays** [comment]
@gt150 @danblah it looks like there was an issue with some draft versions of the citations getting through, which was creating the duplicates that showed. I've updated the script so drafts are disallowed from publishing on the live site, and the issue should now be fixed.

**Comment by danblah** [comment]
Looks fixed!
