### ISSUE TITLE
[mobile] eliminate horizontal scroll on law & reg tracker items in lists, only include name button

### ISSUE THREAD

**Issue by katiewilson21** [ResetNetwork/recoding-tech#65]
on detail page of each iteam, ideally change the horizontal scroll to a vertical orientation, like this: 
![Screen Shot 2022-01-20 at 11 25 43 AM](https://user-images.githubusercontent.com/84089903/150380186-223e5b62-1c22-468c-b33d-a2fe6a983999.png)

**Comment by rudietuesdays** [comment]
Gotcha, definitely can do. Any specific space or divider between these cards, when there's a list of more than one?

**Comment by rudietuesdays** [comment]
@katiewilson21 updated on the dev site!

**Comment by katiewilson21** [comment]
@rudietuesdays looks great! sorry for wording this confusingly, but on the list view (on issue pages or on the policy tracker page) could we just display the name card with the beige background, and not any of the other info about each law? and then when someone clicks the detail page shows the card with all the info? i think it’s too much info for the page when it’s all expanded in the list on mobile. lmk what you think

**Comment by rudietuesdays** [comment]
@katiewilson21 ah gotcha. Yes, we can do that, but not sure if it'll be ready by Friday if we're launching then. Is that ok?

**Comment by gt150** [comment]
@rudietuesdays we're aiming to launch next Friday, so if you can fix before then we'd be good.

**Comment by rudietuesdays** [comment]
As per the newly implemented test workflow, this update has been pushed to the test site for review. Please let me know if it looks ready and if so, I'll push live!

**Comment by harumhelmy** [comment]
Hi @katiewilson21 @gt150, can y'all test Rae's changes on mobile? Should be up on https://test.recoding.tech

**Comment by katiewilson21** [comment]
looks good! only thing is that when the details are expanded, the lines get kind of wonky when the number of lines in each column don't match -- hard for legibility
![IMG_8AAF758E8059-1](https://user-images.githubusercontent.com/84089903/156398892-813f08fb-8699-4184-b3b0-630a3df9b5c4.jpeg)

**Comment by harumhelmy** [comment]
@rudietuesdays, flagging for you Katie's comment above ^
