### ISSUE TITLE
Let's get a test.recoding.tech going with cloudflare in front as production-quality candidate to test

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#70]

**Comment by danblah** [comment]
when i say password protected, i mean not using the netlify pwd, but cloudflare access (so we can test and ee how the site works with caching)

**Comment by danblah** [comment]
Bump bump! Eta @jheretic or @rudietuesdays or @harumhelmy?

**Comment by jheretic** [comment]
We have an instance set up for this at https://recoding-tech-testing.netlify.app/ (dataset is a little screwed up on this instance while I'm using it for testing, so please ignore the empty bits for now). I can set it up on cloudflare as well.

**Comment by danblah** [comment]
sweet, yes... lets get www.recoding.tech (https://recoding-tech-v2.netlify.app/) and test.recoding.tech (https://recoding-tech-testing.netlify.app/) going w/o netlify passwords going, but  both behind cloudflare access as soon as possible so we can see what if any cf issues arise.
