### ISSUE TITLE
Path to GOING LIVE!!!

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#73]
@jheretic @harumhelmy and @rudietuesdays please update the follwoing
* ETA for #23
* ETA for #62 
* ETA for #70 
* ETA for #71 

Resolving these issues are your requirement for this release candidate.

@gt150 please update the following:
* ETA for #69
* ETA for #68
* What if any additional content do you have on the list before going live and what's the ETA for that? 

Resolving these issues are your requirement for this release candidate.

I'm calling GO LIVE this time next week, 5-Feb until I see ETA's that don't allow for it!

All the remaining issues will be prioritized for future releases.

**Comment by harumhelmy** [comment]
Hey y'all! ETA updates below

**ETA by 2/4:**
#80: @harumhelmy is working on this
#75: @rudietuesdays is working on this 

**ETA by 2/11:**
#70: @jheretic is owning
#62, #44, #23, #76: these are related to citations, @jheretic is owning
