### ISSUE TITLE
Need law and regulation tracker to sort by last updated

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#75]
Is it possible to sort the list by last updated?

**Comment by danblah** [comment]
Can y'all come back with an eta for this?

**Comment by rudietuesdays** [comment]
@gt150 sort by last updated in the CMS, or by the column that says when the policy action was last updated?

Can do the former by tomorrow, latter by end of week.

**Comment by gt150** [comment]
@rudietuesdays I need the latter. When the policy action was last updated.

**Comment by rudietuesdays** [comment]
@gt150 updated and ready for review

**Comment by gt150** [comment]
@rudietuesdays thanks. I'm not seeing any change when I look at the law and regulation tracker. I cleared my cache, etc., but still seeing this.
<img width="1155" alt="Screen Shot 2022-02-04 at 10 46 40 AM" src="https://user-images.githubusercontent.com/9727494/152558957-a71bc590-e025-41da-aa6c-feb82c7189e4.png">
.

**Comment by rudietuesdays** [comment]
Hm, I just checked and I'm seeing the following:
![Screen Shot 2022-02-04 at 10 52 28 AM](https://user-images.githubusercontent.com/10843135/152559941-789565e4-6ce0-4636-831b-bcaffb5b7123.png)

Could you try in a private window or different browser? Maybe the cache needs some more time to update?

**Comment by gt150** [comment]
@rudietuesdays alright, I don't know what's going on with Chrome, but I do see it now working with Mozilla and Safari. Could there a be a specific issue with Chrome, or do you think it's just a caching issue?

**Comment by rudietuesdays** [comment]
@gt150 yeah my best guess is caching! If it persists over a long period of time (like longer than a day) we can look into it, but I don't think there's anything browser specific in our code that would cause this.

**Comment by danblah** [comment]
Just tested in chrome. i did a cmd+shift+r to clear the local cache and then opened up an incognito window. both show the same results above. i went into site settings, and manually removed all content and cookies, re logged in... same results.

i open up https://recoding-tech-v2.netlify.app/tracker with firefox, see what you see @rudietuesdays, the new updated information.

Weirdly, on android chrome and firefox react the same... not sorting correctly.

When incorrectly sorted, the records are correct... i see that "Journalism Competition and Preservation Act of 2021 (S.673)" was last updated Feb 2, 2022, its jut most rising to the top.

That confirms this is a non-caching bug to me.

**Comment by harumhelmy** [comment]
Just pushed a fix for this!

**Comment by danblah** [comment]
This is
