### ISSUE TITLE
Can we hide quick start guides for initial launch?

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#77]
I'd like to hide the quick start guides for launch. I won't be able to have enough of them ready to fill the bottom of the page and I need to prioritize other things.

**Comment by danblah** [comment]
@rudietuesdays and @harumhelmy will this section auto hide if there are no guides and if not can we do that and get an eta for such?

**Comment by rudietuesdays** [comment]
@gt150 @danblah As long as no guides are published, they won't show up as related items. I went ahead and unpublished both guides; their content is all still in the CMS and the only difference is their status is now unpublished. I also removed the guides section from the homepage, and we can add it back in when we're ready.

**Comment by danblah** [comment]
Thank you, closing this.
