### ISSUE TITLE
Reducing the blank space on homepage

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#78]
@harumhelmy @katiewilson21 I'm looking for some short-term options to reduce the blank space on the homepage after the box for the featured article. Is it possible to add a few more featured articles? Can we cut the number of headlines and highlight to 3 rather than 5?

**Comment by harumhelmy** [comment]
Both are possible @gt150! Cutting the number of headlines to 3 is a really quick fix, and enabling multiple featured articles is marginally more involved. Just lmk which one you want to move forward with. 

Fwiw, here's how the fewer headlines look on my local dev env: 
![Screen Shot 2022-02-02 at 13 34 49](https://user-images.githubusercontent.com/13320420/152216359-7e5a3713-60b9-43e1-b87f-a24d14aaf09c.png)

**Comment by gt150** [comment]
@harumhelmy let's do that for now. Once we get past launch, we'll revisit.

**Comment by rudietuesdays** [comment]
@gt150 is this good to close out?

**Comment by gt150** [comment]
@rudietuesdays yes you can close out.

**Comment by rudietuesdays** [comment]
Thanks!
