### ISSUE TITLE
Spinny logo is glitchy, moves/jiggles, and freeze/skips

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#8]
Until we resolve, can we remove that rotating action?

**Comment by rudietuesdays** [comment]
Trivial fix, can be done by early next week

**Comment by danblah** [comment]
Boom! Lemme know when something to test!

**Comment by katiewilson21** [comment]
Can we remove the animation entirely? Not sure if that's what you're saying here, but please do!

**Comment by rudietuesdays** [comment]
Is there a preferred hover state? For accessibility, the link should visibly change somehow (doesn't have to be nearly as much, just some visible cue!)

**Comment by katiewilson21** [comment]
Noted! Can we do a thin black underline? or I can give you an svg / codes for an alt color state if you think that's better for accessibility.

**Comment by rudietuesdays** [comment]
Yes, updated!
