### ISSUE TITLE
dev site is down

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#88]
@jheretic @rudietuesdays  the whole dev site is down.
<img width="1412" alt="Screen Shot 2022-02-22 at 12 08 03 PM" src="https://user-images.githubusercontent.com/9727494/155182493-975ba059-c148-4db0-8488-18ab68542e6c.png">

**Comment by harumhelmy** [comment]
It's back up now -- I did experience this down period too, we'll be looking at the logs to see what happened. Sorry about the alarm @gt150 !

**Comment by gt150** [comment]
@harumhelmy thanks for letting me know.
