### ISSUE TITLE
Search is missing in top right

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#9]
see https://www.figma.com/file/L9szOsvQdhyumMOGEz4VnI/Recoding.tech-Wireframes?node-id=528%3A10788

**Comment by rudietuesdays** [comment]
Trivial fix, can be done by early next week

**Comment by danblah** [comment]
Rocking! Lemme know when something to test!

**Comment by rudietuesdays** [comment]
Ready for testing on staging
