### ISSUE TITLE
Require authentication to view https://recoding-tech-v2.netlify.app but not recoding.tech

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#91]
Goal is keep crawlers and non dev folks from hanging out on https://recoding-tech-v2.netlify.app/

**Comment by jheretic** [comment]
We'll tweak the robots.txt and such to make sure it's not being picked up by crawlers (I'll leave this issue open until that's all done) but unfortunately we can't remove the `*.netlify.app` URL or separately password code it, as it's essentially the same site.
