### ISSUE TITLE
Website is slow to load

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#95]
Clocking in at over 3s for the first load and then over 2.5s for subsequent reloads. There's also this stall that happens on all loads.

**Comment by danblah** [comment]
Oh and should've said, both true when going to recoding.tech and https://recoding-tech-v2.netlify.app/

**Comment by jheretic** [comment]
There are some performance fixes on the test branch that should drop that to between .6 and 1.3, when that gets merged to production (just pending some reviews from various folks). I also turned on asset optimization on Netlify. If that ends up not feeling sufficient, there's more optimization we can do.
