### ISSUE TITLE
uploading a file to recoding.tech 

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#97]
@harumhelmy @rudietuesdays is it possible to upload a file to recoding.tech. Basically I need to host something on recoding so I can then link to it on a page.

**Comment by harumhelmy** [comment]
This is possible!

**Comment by harumhelmy** [comment]
This is in progress -- draft PR here: #98

**Comment by gt150** [comment]
@harumhelmy I'm not seeing that option on my end.
![Screen Shot 2022-03-02 at 9 18 22 AM](https://user-images.githubusercontent.com/9727494/156379206-9495cbfb-8bfa-43dc-bdd3-d4230afea7ac.png)
.

**Comment by gt150** [comment]
@harumhelmy Yep, working now. Thanks!
